//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTest_001
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Subbranch_SaleInfo
    {
        public int saleID { get; set; }
        public string saleNo { get; set; }
        public int accID { get; set; }
        public int isRetail { get; set; }
        public int uid { get; set; }
        public Nullable<System.DateTime> saleTime { get; set; }
        public Nullable<System.DateTime> insertTime { get; set; }
        public Nullable<int> saleKind { get; set; }
        public Nullable<double> saleNum { get; set; }
        public int payType { get; set; }
        public Nullable<decimal> AbleMoney { get; set; }
        public Nullable<decimal> RealMoney { get; set; }
        public Nullable<decimal> DiffMoney { get; set; }
        public Nullable<int> StoreTimes { get; set; }
        public Nullable<decimal> StoreMoney { get; set; }
        public Nullable<decimal> CashMoney { get; set; }
        public Nullable<decimal> CardMoney { get; set; }
        public Nullable<decimal> UnpaidMoney { get; set; }
        public Nullable<decimal> ReturnBackMoney { get; set; }
        public Nullable<int> isSendSMS { get; set; }
        public Nullable<int> isPrintTicket { get; set; }
        public Nullable<int> operatorID { get; set; }
        public Nullable<System.DateTime> operatorTime { get; set; }
        public string operatorIP { get; set; }
        public string exJson { get; set; }
        public Nullable<int> zt { get; set; }
        public Nullable<int> CouponMoney { get; set; }
        public Nullable<int> CouponID { get; set; }
        public string CouponCode { get; set; }
        public Nullable<long> SerialNum { get; set; }
        public Nullable<decimal> AlipayMoney { get; set; }
        public Nullable<int> saleFlag { get; set; }
        public Nullable<decimal> IntegralMoney { get; set; }
        public Nullable<decimal> IntegralUsed { get; set; }
        public string wholeRemark { get; set; }
        public string EnterpriseId { get; set; }
    }
}
