//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTest_001
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Subbranch_GoodsInfo
    {
        public long Id { get; set; }
        public string EnterpriseId { get; set; }
        public string GoodsNo { get; set; }
        public string GoodsSerialNum { get; set; }
        public string GoodsName { get; set; }
        public Nullable<int> GoodsCategoryID { get; set; }
        public Nullable<long> GoodsMaxClassId { get; set; }
        public string GoodsMaxClassName { get; set; }
        public Nullable<long> GoodsMinClassId { get; set; }
        public string GoodsMinClassName { get; set; }
        public Nullable<decimal> InPrice { get; set; }
        public decimal SalePrice { get; set; }
        public string ExtInfo { get; set; }
        public string Spec { get; set; }
        public string Remark { get; set; }
        public decimal GoodsStock { get; set; }
        public Nullable<decimal> LimitLower { get; set; }
        public Nullable<decimal> LimitUpper { get; set; }
        public long Operator { get; set; }
        public System.DateTime OperatorTime { get; set; }
    }
}
