//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTest_001
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Subbranch_AuthCode
    {
        public int Id { get; set; }
        public string PhoneNumber { get; set; }
        public string EnterpriseId { get; set; }
        public short AuthCodeType { get; set; }
        public string AuthCode { get; set; }
        public short AuthStatus { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> CreateOperatorID { get; set; }
        public string CreateOperatorIP { get; set; }
        public Nullable<System.DateTime> VerifyTime { get; set; }
        public Nullable<int> VerifyOperatorID { get; set; }
        public string VerifyOperatorIP { get; set; }
    }
}
