//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTest_001
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Subbranch_Goods_Sku
    {
        public int gsId { get; set; }
        public Nullable<int> gid { get; set; }
        public Nullable<decimal> gsQuantity { get; set; }
        public Nullable<decimal> gsDiscount { get; set; }
        public Nullable<decimal> gsPrice { get; set; }
        public Nullable<decimal> gsCostPrice { get; set; }
        public string gsBarcode { get; set; }
        public Nullable<System.DateTime> gsCheckDate { get; set; }
        public Nullable<System.DateTime> gsTime { get; set; }
        public string EnterpriseId { get; set; }
        public string extendVal { get; set; }
        public Nullable<int> IsCalculatePoint { get; set; }
        public Nullable<decimal> LimitUpper { get; set; }
        public Nullable<decimal> LimitLower { get; set; }
    }
}
