//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTest_001
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Subbranch_OnlineMallProduct
    {
        public int Id { get; set; }
        public int FrontOrderProjectBusId { get; set; }
        public string DisplayName { get; set; }
        public decimal SalePrice { get; set; }
        public short AllowBuy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public int ModifierId { get; set; }
        public short VersionCategory { get; set; }
    }
}
