//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTest_001
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Subbranch_AllocationItem
    {
        public int Id { get; set; }
        public Nullable<long> AllocationId { get; set; }
        public string GoodsNo { get; set; }
        public string GoodsName { get; set; }
        public Nullable<long> GoodsMaxId { get; set; }
        public string GoodsMaxName { get; set; }
        public Nullable<long> GoodsMinId { get; set; }
        public string GoodsMinName { get; set; }
        public Nullable<decimal> AllocationInPrice { get; set; }
        public Nullable<decimal> Number { get; set; }
        public Nullable<decimal> Amount { get; set; }
    }
}
