//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTest_001
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Subbranch_Login_Log
    {
        public int Id { get; set; }
        public int LoginId { get; set; }
        public Nullable<int> OwnerId { get; set; }
        public string EnterpriseId { get; set; }
        public System.DateTime LoginTime { get; set; }
        public Nullable<System.DateTime> LogoutTime { get; set; }
        public string LoginIP { get; set; }
        public string LoginBrowser { get; set; }
        public Nullable<int> ClientType { get; set; }
    }
}
