//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTest_001
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Subbranch_OnlineMallOrder
    {
        public int Id { get; set; }
        public string Token { get; set; }
        public string EnterpriseId { get; set; }
        public Nullable<System.DateTime> BuyDate { get; set; }
        public Nullable<short> HasFinished { get; set; }
        public Nullable<decimal> SummarySale { get; set; }
        public Nullable<decimal> SummaryReturn { get; set; }
        public Nullable<decimal> SummaryOrderPaid { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<int> ModifierId { get; set; }
        public string FrontOrderNo { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> Status { get; set; }
        public string OperatorName { get; set; }
    }
}
