//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTest_001
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Subbranch_GoodsStock_ChangeLog
    {
        public int Id { get; set; }
        public string EnterpriseId { get; set; }
        public Nullable<int> FrontAccountId { get; set; }
        public Nullable<long> Gid { get; set; }
        public string GoodsNo { get; set; }
        public string GoodsName { get; set; }
        public string GoodsMaxClassName { get; set; }
        public Nullable<long> GoodsMaxClassId { get; set; }
        public string GoodsMinClassName { get; set; }
        public Nullable<long> GoodsMinClassId { get; set; }
        public int ChangeType { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<decimal> StockBefore { get; set; }
        public Nullable<decimal> StockAfter { get; set; }
        public Nullable<decimal> ChangeQuantity { get; set; }
        public Nullable<decimal> MoneyCharge { get; set; }
        public Nullable<int> OperatorId { get; set; }
        public string Remark { get; set; }
    }
}
