//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTest_001
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Subbranch_GoodPic
    {
        public long Id { get; set; }
        public Nullable<int> Score { get; set; }
        public string PicUrl { get; set; }
        public string UrlPrefix { get; set; }
        public long Gid { get; set; }
        public System.DateTime OperatorTime { get; set; }
        public long OperatorId { get; set; }
        public string EnterpriseId { get; set; }
    }
}
