//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTest_001
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Subbranch_Allocation
    {
        public int Id { get; set; }
        public string SerialNumbers { get; set; }
        public Nullable<long> FromShopId { get; set; }
        public Nullable<long> ToShopId { get; set; }
        public Nullable<decimal> TotalMoneyAmount { get; set; }
        public Nullable<decimal> TotalGoodsAmount { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> Type { get; set; }
        public string Remark { get; set; }
        public Nullable<long> Operator { get; set; }
        public string RejectReason { get; set; }
        public string EnterpriseId { get; set; }
    }
}
