//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTest_001
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Subbranch_OnlineMallOrderDetailTemp
    {
        public long Id { get; set; }
        public long OrderId { get; set; }
        public int QoutaNumber { get; set; }
        public Nullable<int> PurchaseLength { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<decimal> SalePrice { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<int> ModifierId { get; set; }
        public Nullable<long> QoutaId { get; set; }
    }
}
