//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTest_001
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Subbranch_EnterpriseInfo
    {
        public int Id { get; set; }
        public string EnterpriseId { get; set; }
        public Nullable<int> IndustryProductId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public int ModifierId { get; set; }
        public short HasImportedMember { get; set; }
        public short HasImportedGoods { get; set; }
        public string UniqueShopIdPrefix { get; set; }
        public int UniqueShopCounter { get; set; }
        public short HasBoughtProduct { get; set; }
    }
}
