//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTest_001
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Subbranch_Qouta_Log
    {
        public long Id { get; set; }
        public Nullable<long> QoutaId { get; set; }
        public Nullable<System.DateTime> BindDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> Numbers { get; set; }
        public Nullable<int> DurationDay { get; set; }
        public string Remark { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string EnterpriseId { get; set; }
        public Nullable<long> OperatorId { get; set; }
        public string QoutaIdList { get; set; }
    }
}
