//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTest_001
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Subbranch_SaleList
    {
        public long saleListID { get; set; }
        public string maxClass { get; set; }
        public string minClass { get; set; }
        public string Specification { get; set; }
        public string GoodsName { get; set; }
        public Nullable<double> GoodsNum { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<System.DateTime> saleTime { get; set; }
        public Nullable<long> userID { get; set; }
        public Nullable<long> accID { get; set; }
        public Nullable<double> Discount { get; set; }
        public string saleNo { get; set; }
        public string Remark { get; set; }
        public Nullable<int> maxClassID { get; set; }
        public Nullable<int> minClassID { get; set; }
        public Nullable<int> GoodsID { get; set; }
        public Nullable<int> isIntegral { get; set; }
        public Nullable<decimal> CostPrice { get; set; }
        public Nullable<decimal> RealMoney { get; set; }
        public Nullable<System.DateTime> insertTime { get; set; }
        public Nullable<decimal> AbleMoney { get; set; }
        public Nullable<int> CashierID { get; set; }
        public Nullable<int> saleID { get; set; }
        public Nullable<int> isRetail { get; set; }
        public Nullable<System.DateTime> operatorTime { get; set; }
        public Nullable<int> operatorID { get; set; }
        public Nullable<int> returnStatus { get; set; }
        public Nullable<int> returnFlag { get; set; }
        public string returnDesc { get; set; }
        public string returnRemark { get; set; }
        public Nullable<System.DateTime> returnTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<decimal> FixMoney { get; set; }
        public Nullable<int> pt { get; set; }
        public Nullable<int> zt { get; set; }
        public Nullable<int> ifpay { get; set; }
        public Nullable<long> SerialNum { get; set; }
        public Nullable<int> TimeCardId { get; set; }
        public Nullable<int> IsExtend { get; set; }
        public Nullable<int> SkuId { get; set; }
        public string AdditionalSaleId { get; set; }
        public Nullable<int> exchangesFlag { get; set; }
        public Nullable<decimal> exchangesMakingUpDifferences { get; set; }
        public Nullable<int> exchangesSalesListId { get; set; }
        public string EnterpriseId { get; set; }
    }
}
