//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTest_001
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Subbranch_MemberInfo
    {
        public int Id { get; set; }
        public int FrontAccountId { get; set; }
        public string EnterpriseId { get; set; }
        public Nullable<System.DateTime> RegTime { get; set; }
        public Nullable<int> MemberId { get; set; }
        public string MemberNo { get; set; }
        public string MemberName { get; set; }
        public string MemberPhone { get; set; }
        public string MemberRank { get; set; }
        public Nullable<decimal> MemberIntegral { get; set; }
        public Nullable<decimal> MemberStore { get; set; }
        public string MemberTimes { get; set; }
    }
}
