//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTest_001
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Subbranch_MainStockLog
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> OperDate { get; set; }
        public string CompanyName { get; set; }
        public string CategoryName { get; set; }
        public string GoodsName { get; set; }
        public string ChangeTypeStr { get; set; }
        public Nullable<decimal> OriginalVal { get; set; }
        public Nullable<decimal> EditVal { get; set; }
        public Nullable<decimal> FinalVal { get; set; }
        public Nullable<decimal> MoneyCharge { get; set; }
        public string Operator { get; set; }
        public string Remark { get; set; }
        public string EnterpriseId { get; set; }
        public Nullable<int> accID { get; set; }
        public string SubbranchGoodsNo { get; set; }
        public Nullable<int> gid { get; set; }
    }
}
