//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTest_001
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Subbranch_AccountArea
    {
        public int AccountId { get; set; }
        public int AccountAreaLv1Id { get; set; }
        public int AccountAreaLv2Id { get; set; }
        public string AccountAreaLv1Name { get; set; }
        public string AccountAreaLv2Name { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int ModifierId { get; set; }
        public string EnterpriseId { get; set; }
    }
}
