//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTest_001
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Subbranch_Goods_Attribute
    {
        public int gaId { get; set; }
        public string gaName { get; set; }
        public Nullable<int> gaType { get; set; }
        public string gaRemark { get; set; }
        public Nullable<System.DateTime> gaTime { get; set; }
        public int gaAlive { get; set; }
        public string EnterpriseId { get; set; }
    }
}
