//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTest_001
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Subbranch_Shop
    {
        public int Id { get; set; }
        public int FrontAccountId { get; set; }
        public string ShopName { get; set; }
        public string ShopManager { get; set; }
        public string PhoneNumber { get; set; }
        public string ShopPhone { get; set; }
        public string EnterpriseId { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> RegTime { get; set; }
        public Nullable<short> Status { get; set; }
        public Nullable<System.DateTime> VersionDueDate { get; set; }
        public string Remark { get; set; }
        public int VersionProductId { get; set; }
        public string VersionName { get; set; }
        public Nullable<System.DateTime> VersionActiveDate { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public int ModifierId { get; set; }
        public string UniqueShopId { get; set; }
    }
}
