//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTest_001
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Subbranch_GoodsStock
    {
        public int Id { get; set; }
        public string EnterpriseId { get; set; }
        public Nullable<int> FrontAccountId { get; set; }
        public int GoodsId { get; set; }
        public Nullable<decimal> GoodsStock { get; set; }
        public Nullable<System.DateTime> LastModifyDate { get; set; }
        public string ExtInfo { get; set; }
    }
}
